table payments
	lineageTag: f6230cc2-6cb1-494c-aebb-c7b81acc9814

	column trip_id
		dataType: string
		lineageTag: c540811f-b5c0-47dc-9e3e-869aa1cd1a62
		summarizeBy: none
		sourceColumn: trip_id

		annotation SummarizationSetBy = Automatic

	column trip
		dataType: string
		lineageTag: 32e7dddb-3775-424f-91d0-42d17e394fe4
		summarizeBy: none
		sourceColumn: trip

		annotation SummarizationSetBy = Automatic

	column debtor
		dataType: string
		lineageTag: 2437ff5b-f7e4-4f20-b606-b792661ed811
		summarizeBy: none
		sourceColumn: debtor

		annotation SummarizationSetBy = Automatic

	column lander
		dataType: string
		lineageTag: 79eeff98-32af-4c04-be2c-940c2e88c4c5
		summarizeBy: none
		sourceColumn: lander

		annotation SummarizationSetBy = Automatic

	column currency
		dataType: string
		lineageTag: 46ff1b33-0dd1-4090-babf-5d1e170ea26f
		summarizeBy: none
		sourceColumn: currency

		annotation SummarizationSetBy = Automatic

	column rate
		dataType: int64
		formatString: 0
		lineageTag: 04872a96-7353-4f61-a64f-b5aedc1c344f
		summarizeBy: sum
		sourceColumn: rate

		annotation SummarizationSetBy = Automatic

	column monto
		dataType: double
		lineageTag: 921de719-b22a-4006-bca6-ac4f3a138794
		summarizeBy: sum
		sourceColumn: monto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column monto_lps
		dataType: double
		lineageTag: 0e4042ed-744a-432e-82a6-c9a0a5c610c2
		summarizeBy: sum
		sourceColumn: monto_lps

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition payments = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\GitHub\trip-expense-management\data-pipelines\database\silver\payments.csv"),[Delimiter=",", Columns=8, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"trip_id", type text}, {"trip", type text}, {"debtor", type text}, {"lander", type text}, {"currency", type text}, {"rate", Int64.Type}, {"monto", type number}, {"monto_lps", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

