table balances
	lineageTag: 05dedd8c-c8ca-4d8f-9db5-6c103b62bdc2

	column id
		dataType: string
		lineageTag: 863e8370-b299-432e-a4d0-340f9ab377cc
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column traveler
		dataType: string
		lineageTag: e57c7512-4e16-4a69-8db4-7b5d95d17fc4
		summarizeBy: none
		sourceColumn: traveler

		annotation SummarizationSetBy = Automatic

	column trip_id
		dataType: string
		lineageTag: 4d7ad55e-0cfd-4555-94a0-d4343f014de2
		summarizeBy: none
		sourceColumn: trip_id

		annotation SummarizationSetBy = Automatic

	column paid_lps
		dataType: double
		lineageTag: 628b8d62-5d03-4742-b83f-886a567c5a5a
		summarizeBy: sum
		sourceColumn: paid_lps

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column owed_lps
		dataType: double
		lineageTag: ea444396-c972-4844-995c-f3659bb7bb3b
		summarizeBy: sum
		sourceColumn: owed_lps

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column payment_sent_lps
		dataType: double
		lineageTag: d9634176-4c5b-4ee7-9d5f-d0ec90564bfb
		summarizeBy: sum
		sourceColumn: payment_sent_lps

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column payment_received_lps
		dataType: double
		lineageTag: c50c10f8-ff43-4385-9e0f-a909382e5e45
		summarizeBy: sum
		sourceColumn: payment_received_lps

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column net_balance_lps
		dataType: double
		lineageTag: 6d66e365-678d-4431-bea2-93f2dccf9b81
		summarizeBy: sum
		sourceColumn: net_balance_lps

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition balances = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\GitHub\trip-expense-management\data-pipelines\database\silver\balances.csv"), [Delimiter = ",", Columns = 8, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"id", type text}, {"traveler", type text}, {"trip_id", type text}, {"paid_lps", type number}, {"owed_lps", type number}, {"payment_sent_lps", type number}, {"payment_received_lps", type number}, {"net_balance_lps", type number}})
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

