table expense_shares
	lineageTag: 4347ab67-c0f6-4f18-9649-6daa44d63db2

	column expense_id
		dataType: string
		lineageTag: 7a835e92-f0d5-4f9a-bd9e-67dfaf3a2092
		summarizeBy: none
		sourceColumn: expense_id

		annotation SummarizationSetBy = Automatic

	column trip_id
		dataType: string
		lineageTag: 0f9fd55a-d581-4298-826c-39934c523a51
		summarizeBy: none
		sourceColumn: trip_id

		annotation SummarizationSetBy = Automatic

	column traveler_id
		dataType: string
		lineageTag: f0a9983c-f01d-46d6-b93a-593c827059b8
		summarizeBy: none
		sourceColumn: traveler_id

		annotation SummarizationSetBy = Automatic

	column debtor
		dataType: string
		lineageTag: 80eb17d9-320c-4015-945c-15c28ff40b00
		summarizeBy: none
		sourceColumn: debtor

		annotation SummarizationSetBy = Automatic

	column lander
		dataType: string
		lineageTag: 9e0a02dc-f705-40a4-a038-5ae86fb5546e
		summarizeBy: none
		sourceColumn: lander

		annotation SummarizationSetBy = Automatic

	column participant_count
		dataType: int64
		formatString: 0
		lineageTag: 1fdb8f5a-e77b-4260-94f2-0ec0611d4776
		summarizeBy: sum
		sourceColumn: participant_count

		annotation SummarizationSetBy = Automatic

	column share_lps
		dataType: double
		lineageTag: 058323e9-4413-4102-9417-5d4d0ef3fb34
		summarizeBy: sum
		sourceColumn: share_lps

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column share_usd
		dataType: double
		lineageTag: c257fcff-8b89-45cc-aa64-35525bbb38b2
		summarizeBy: sum
		sourceColumn: share_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition expense_shares = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\GitHub\trip-expense-management\data-pipelines\database\silver\expense_shares.csv"),[Delimiter=",", Columns=8, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"expense_id", type text}, {"trip_id", type text}, {"traveler_id", type text}, {"debtor", type text}, {"lander", type text}, {"participant_count", Int64.Type}, {"share_lps", type number}, {"share_usd", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

