table travelers
	lineageTag: 9323f333-99bc-49ef-8cee-d33c5a3fdc51

	column id
		dataType: string
		lineageTag: 2bee4afe-5419-451d-818e-ead91f311f3e
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column traveler
		dataType: string
		lineageTag: 19eefc3e-628c-4608-9d01-69fc3703f4cd
		summarizeBy: none
		sourceColumn: traveler

		annotation SummarizationSetBy = Automatic

	partition travelers = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\GitHub\trip-expense-management\data-pipelines\database\silver\travelers.csv"), [Delimiter = ",", Columns = 2, QuoteStyle = QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", type text}, {"traveler", type text}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

