table trips
	lineageTag: 5f83268e-9fd8-4018-a857-9ffeae9620af

	column id
		dataType: string
		lineageTag: 26d301ef-fd52-4768-b894-159f84004b42
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column trip
		dataType: string
		lineageTag: 96b2d5b2-0545-4384-9a88-d62abe9f61c2
		summarizeBy: none
		sourceColumn: trip

		annotation SummarizationSetBy = Automatic

	column destination
		dataType: string
		lineageTag: 71f6f067-0e1d-449e-8597-fcbb71ec6232
		summarizeBy: none
		sourceColumn: destination

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c211bfd4-3c26-4cf9-9918-727d4bbc0c26
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 52fbd307-1b17-43bb-98eb-6ace60199928
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition trips = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\GitHub\trip-expense-management\data-pipelines\database\silver\trips.csv"), [Delimiter = ",", Columns = 5, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"id", type text}, {"trip", type text}, {"destination", type text}, {"start_date", type date}, {"end_date", type date}})
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

